@startuml
skinparam defaultTextAlignment center
skinparam SequenceMessageAlign center

Actor Chef as ch
participant System as sy
ch -> sy : apriFoglioRiepilogativo(Evento)
ch <-- sy : FoglioRiepilogativo

opt
    loop
        alt 2 : aggiungi compito
            ch -> sy : aggiungiCompito(ProceduraDiCucina)
            ch <-- sy : OK
        else 2a: rimuovi compito
            ch -> sy : rimuoviCompito(Compito)
            ch <-- sy : OK
        end
    end

    opt 3: ordinare elenco
        ch -> sy : ordinaElenco(Compito, posizione)
        ch <-- sy : OK
    end
    loop
        opt 4: consultare tabellone
            ch -> sy : consultaTabellone()
            ch <-- sy : TabelloneDeiTurni
        end
        alt 5: assegnare compiti
            ch -> sy : assegnaCompito(Compito, Turno, Cuoco?, Quantita?, StimaTempo?, difficolta?)
            ch <-- sy : Foglio aggiornato
            else eccezione 5a
            ch -> sy : assegnaCompito(Compito, Turno, Cuoco?, Quantita?, StimaTempo?, difficolta?)
            ch <--X sy : cuoco non disponibile in turno
            else eccezione 5b
            ch -> sy : assegnaCompito(Compito, Turno, Cuoco?, Quantita?, StimaTempo?, difficolta?)
            ch <--X sy : tempo compito eccede tempo diponibile
            else 5a: elimina assegnamento
            ch -> sy : eliminaAssegnamento(Compito)
            ch <-- sy : Foglio aggiornato
        end

    end

end
@enduml