@startuml
skinparam defaultTextAlignment center
skinparam SequenceMessageAlign center

Actor Chef as ch
participant System as sy
ch -> sy : apriFoglioRiepilogativo(Evento: ev)
ch <-- sy : FoglioRiepilogativo

opt
    loop
        alt 2 : aggiungi procedura
            ch -> sy : aggiungiCompito(ProceduraDiCucina)
            ch <-- sy : OK
        else 2a: rimuovi procedura
            ch -> sy : rimmuoviCompito(ProceduraDiCucina)
            ch <-- sy : OK
        end
    end

    opt 3: ordinare elenco
        ch -> sy : ordinaElenco(procedura, posizione)
        ch <-- sy : OK
    end
    loop
        opt 4: consultare tabellone
            ch -> sy : consultaTabellone()
            ch <-- sy : TabelloneDeiTurni
        end
        alt 5: assegnare compiti
            ch -> sy : creaCompito(ProceduraDiCucina, Turno, Cuoco?, Quantita?, StimaTempo?, difficolta?)
            ch <-- sy : Foglio aggiornato
            else 5a: modifica compito
            ch -> sy : modificaCompito(oldCompito, newCompito)
            ch <-- sy : Foglio aggiornato
            else eccezione 5a
            ch -> sy : modificaCompito(oldCompito, newCompito)
            ch <--X sy : cuoco non disponibile in turno
            else eccezione 5b
            ch -> sy : modificaCompito(oldCompito, newCompito)
            ch <--X sy : tempo compito eccede tempo diponibile
            else 5b: elimina compito
            ch -> sy : eliminaCompito(compito)
            ch <-- sy : Foglio aggiornato
        end

    end

end
@enduml